baseurl = "https://ks-no.github.io/"
languageCode = "nb-no"
title = "KS Fiks dokumentasjon"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "KS"
	description = "Dokumentasjonen for KS sin FIKS plattform"
	copyright = "KS"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/ks-no/ks-no.github.io"

	version = "1.0.0"
	logo = "images/ks-logo.svg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["styles.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "indigo"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "ks-no"
	email   = "svarut-utvikling@ks.no"


[[menu.main]]
	name   = "Minside"
	url    = "minside/"
	weight = 0

[[menu.main]]
	name   = "Fiks platform"
	url    = "fiks-platform/"
	weight = 0

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
