baseURL = "/"

languageCode = "nb-no"
defaultContentLanguage = "no"
title = "KS Fiks"
theme = "docdock"
#themesdir = "themes"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

preservetaxonomynames = true
pluralizeListTitles = false

# [Languages]
# [Languages.en]
# title = "Documentation for Hugo docDock"
# weight = 1
# languageName = "English"
# 
# [Languages.fr]
# title = "Documentation du thème docDock"
# weight = 2
# languageName = "Français"

enableGitInfo = true

#Ser ikke ut til å fungere
[frontmatter]
date = ["date","publishDate", "lastmod"]
lastmod = ["lastmod", "date", "publishDate"]
publishDate = [":git", "lastmod", "publishDate", "date"]
expiryDate = ["expiryDate"]


[params]
editURL = "https://github.com/ks-no/ks-no.github.io/edit/source/content/"
showVisitedLinks = false # default is false
themeStyle = "original" # "original" or "flex" # default "flex"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "title" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = true # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = true

[outputs]
home = [ "HTML", "JSON", "RSS"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> <label>Github repo</label>"
identifier = "ds"
url = "https://github.com/ks-no/ks-no.github.io"
weight = 10
